name: reactive_forms_lbc
description: This is a set of widgets for reactive_forms package in Listener/Builder/Consumer paradigm the same as bloc library does.
repository: https://github.com/artflutter/reactive_forms_widgets/tree/master/packages/reactive_forms_lbc
issue_tracker: https://github.com/artflutter/reactive_forms_widgets/issues

version: 5.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  reactive_forms: ">=16.0.0 <19.0.0"
  nested: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
